=== cuker/merchant-gateways/lib/merchant_gateways/tests/billing/gateways/schemas/xmlpay/XMLPay_2001.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="simpleType">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0">
				<xs:element ref="enumeration" maxOccurs="unbounded"/>
				<xs:element ref="maxLength"/>
			</xs:choice>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="AuthCodeType"/>
						<xs:enumeration value="BuyerAuthStatusEnum"/>
						<xs:enumeration value="CompanyNameType"/>
						<xs:enumeration value="HostCodeType"/>
						<xs:enumeration value="MatchResultEnum"/>
						<xs:enumeration value="OptionalTransType"/>
						<xs:enumeration value="PayPeriodType"/>
						<xs:enumeration value="ProfileIDType"/>
						<xs:enumeration value="RPDateType"/>
						<xs:enumeration value="RPNameType"/>
						<xs:enumeration value="RPRefType"/>
						<xs:enumeration value="RPStatusType"/>
						<xs:enumeration value="StatusType"/>
						<xs:enumeration value="TransactionUpdateActionEnum"/>
						<xs:enumeration value="VerbosityEnum"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="base" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="string"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sequence">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="element" maxOccurs="unbounded"/>
					<xs:sequence minOccurs="0">
						<xs:element ref="choice"/>
						<xs:element ref="element" minOccurs="0"/>
					</xs:sequence>
				</xs:sequence>
				<xs:sequence>
					<xs:element ref="choice"/>
					<xs:element ref="element" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="schema">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="include"/>
				<xs:element ref="element" maxOccurs="unbounded"/>
				<xs:element ref="simpleType"/>
				<xs:element ref="element" maxOccurs="unbounded"/>
				<xs:element ref="simpleType"/>
				<xs:element ref="element" maxOccurs="unbounded"/>
				<xs:element ref="simpleType"/>
				<xs:element ref="element"/>
				<xs:element ref="simpleType" maxOccurs="unbounded"/>
				<xs:element ref="element" maxOccurs="unbounded"/>
				<xs:element ref="simpleType" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="xsd" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:anyURI">
						<xs:enumeration value="http://www.w3.org/2001/XMLSchema"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="targetNamespace" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:anyURI">
						<xs:enumeration value="http://www.paypal.com/XMLPay"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="maxLength">
		<xs:complexType>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:short">
						<xs:enumeration value="12"/>
						<xs:enumeration value="127"/>
						<xs:enumeration value="128"/>
						<xs:enumeration value="3"/>
						<xs:enumeration value="6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="include">
		<xs:complexType>
			<xs:attribute name="schemaLocation" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="XMLPayTypes.xsd"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="enumeration">
		<xs:complexType>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="A"/>
						<xs:enumeration value="Approve"/>
						<xs:enumeration value="Auth"/>
						<xs:enumeration value="Bi-weekly"/>
						<xs:enumeration value="E"/>
						<xs:enumeration value="Every four weeks"/>
						<xs:enumeration value="F"/>
						<xs:enumeration value="High"/>
						<xs:enumeration value="I"/>
						<xs:enumeration value="Low"/>
						<xs:enumeration value="Match"/>
						<xs:enumeration value="Medium"/>
						<xs:enumeration value="MerchantDecline"/>
						<xs:enumeration value="Monthly"/>
						<xs:enumeration value="N"/>
						<xs:enumeration value="No Match"/>
						<xs:enumeration value="O"/>
						<xs:enumeration value="Off"/>
						<xs:enumeration value="Quarterly"/>
						<xs:enumeration value="Review"/>
						<xs:enumeration value="Sale"/>
						<xs:enumeration value="Semi-monthly"/>
						<xs:enumeration value="Semi-yearly"/>
						<xs:enumeration value="Service Not Available"/>
						<xs:enumeration value="Service Not Requested"/>
						<xs:enumeration value="ServiceDecline"/>
						<xs:enumeration value="U"/>
						<xs:enumeration value="Weekly"/>
						<xs:enumeration value="X"/>
						<xs:enumeration value="Y"/>
						<xs:enumeration value="Yearly"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="element">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="complexType" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="AUActionEnum"/>
						<xs:enumeration value="AUResponseCode"/>
						<xs:enumeration value="AUResponseText"/>
						<xs:enumeration value="AuthCodeType"/>
						<xs:enumeration value="Base64Sha1StringType"/>
						<xs:enumeration value="BuyerAuthMesgType"/>
						<xs:enumeration value="BuyerAuthStatusEnum"/>
						<xs:enumeration value="CommentType"/>
						<xs:enumeration value="CompanyNameType"/>
						<xs:enumeration value="CorrelationIDType"/>
						<xs:enumeration value="CurrencyAmount"/>
						<xs:enumeration value="ECIType"/>
						<xs:enumeration value="ECTokenType"/>
						<xs:enumeration value="EMailType"/>
						<xs:enumeration value="HostCodeType"/>
						<xs:enumeration value="InvNumType"/>
						<xs:enumeration value="MatchResultEnum"/>
						<xs:enumeration value="NameType"/>
						<xs:enumeration value="OptionalTransType"/>
						<xs:enumeration value="PNRefType"/>
						<xs:enumeration value="PPRefType"/>
						<xs:enumeration value="PasswordType"/>
						<xs:enumeration value="PayPeriodType"/>
						<xs:enumeration value="PayerIDType"/>
						<xs:enumeration value="PhoneNumberType"/>
						<xs:enumeration value="ProfileIDType"/>
						<xs:enumeration value="RPDateType"/>
						<xs:enumeration value="RPNameType"/>
						<xs:enumeration value="RPRefType"/>
						<xs:enumeration value="RPStatusType"/>
						<xs:enumeration value="StatusType"/>
						<xs:enumeration value="TenderTypeEnum"/>
						<xs:enumeration value="TransactionUpdateActionEnum"/>
						<xs:enumeration value="UserIdType"/>
						<xs:enumeration value="VerbosityEnum"/>
						<xs:enumeration value="byte"/>
						<xs:enumeration value="date"/>
						<xs:enumeration value="dateTime"/>
						<xs:enumeration value="int"/>
						<xs:enumeration value="string"/>
						<xs:enumeration value="uriReference"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ref">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="AVSResult"/>
						<xs:enumeration value="AccountUpdateRequest"/>
						<xs:enumeration value="AccountUpdateResult"/>
						<xs:enumeration value="Add"/>
						<xs:enumeration value="Address"/>
						<xs:enumeration value="Authorization"/>
						<xs:enumeration value="BuyerAuthResult"/>
						<xs:enumeration value="Cancel"/>
						<xs:enumeration value="Capture"/>
						<xs:enumeration value="Credit"/>
						<xs:enumeration value="DoExpressCheckout"/>
						<xs:enumeration value="ExtData"/>
						<xs:enumeration value="ForceCapture"/>
						<xs:enumeration value="FraudPostprocessResult"/>
						<xs:enumeration value="FraudPreprocessResult"/>
						<xs:enumeration value="GetExpressCheckout"/>
						<xs:enumeration value="GetStatus"/>
						<xs:enumeration value="HTTPCommitResult"/>
						<xs:enumeration value="Inquiry"/>
						<xs:enumeration value="Invoice"/>
						<xs:enumeration value="Modify"/>
						<xs:enumeration value="PayData"/>
						<xs:enumeration value="PayDataAuth"/>
						<xs:enumeration value="PayPalResult"/>
						<xs:enumeration value="Payment"/>
						<xs:enumeration value="ProcessorResult"/>
						<xs:enumeration value="RPData"/>
						<xs:enumeration value="RPPaymentResult"/>
						<xs:enumeration value="Reactivate"/>
						<xs:enumeration value="ReceiptData"/>
						<xs:enumeration value="RecurringProfile"/>
						<xs:enumeration value="RecurringProfileResult"/>
						<xs:enumeration value="RepeatSale"/>
						<xs:enumeration value="RequestAuth"/>
						<xs:enumeration value="RequestData"/>
						<xs:enumeration value="ResponseData"/>
						<xs:enumeration value="Sale"/>
						<xs:enumeration value="SetExpressCheckout"/>
						<xs:enumeration value="Signature"/>
						<xs:enumeration value="Tender"/>
						<xs:enumeration value="Transaction"/>
						<xs:enumeration value="TransactionResult"/>
						<xs:enumeration value="TransactionUpdate"/>
						<xs:enumeration value="UserPass"/>
						<xs:enumeration value="ValidateAuthentication"/>
						<xs:enumeration value="VerifyEnrollment"/>
						<xs:enumeration value="VersionIntegrationTracking"/>
						<xs:enumeration value="Void"/>
						<xs:enumeration value="XMLPayReceipt"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ACHStatus"/>
						<xs:enumeration value="ACSUrl"/>
						<xs:enumeration value="AMEXID"/>
						<xs:enumeration value="AUResponseCode"/>
						<xs:enumeration value="AUResponseText"/>
						<xs:enumeration value="AUSubmitDate"/>
						<xs:enumeration value="AVSResult"/>
						<xs:enumeration value="AccountUpdateRequest"/>
						<xs:enumeration value="AccountUpdateRequests"/>
						<xs:enumeration value="AccountUpdateResult"/>
						<xs:enumeration value="AccountUpdateResults"/>
						<xs:enumeration value="Action"/>
						<xs:enumeration value="Add"/>
						<xs:enumeration value="AdditionalMessages"/>
						<xs:enumeration value="AggregateAmt"/>
						<xs:enumeration value="AggregateOptionalTransAmt"/>
						<xs:enumeration value="Amt"/>
						<xs:enumeration value="AuthCode"/>
						<xs:enumeration value="AuthenticationId"/>
						<xs:enumeration value="Authorization"/>
						<xs:enumeration value="BalanceAmount"/>
						<xs:enumeration value="BillTo"/>
						<xs:enumeration value="BrowserCountryCode"/>
						<xs:enumeration value="BrowserTime"/>
						<xs:enumeration value="BrowserUserAgent"/>
						<xs:enumeration value="BuyerAuthResult"/>
						<xs:enumeration value="CAVV"/>
						<xs:enumeration value="CVResult"/>
						<xs:enumeration value="Cancel"/>
						<xs:enumeration value="Capture"/>
						<xs:enumeration value="CardSecure"/>
						<xs:enumeration value="Comment"/>
						<xs:enumeration value="CompanyName"/>
						<xs:enumeration value="CorrelationID"/>
						<xs:enumeration value="Credit"/>
						<xs:enumeration value="Custom"/>
						<xs:enumeration value="DoExpressCheckout"/>
						<xs:enumeration value="ECI"/>
						<xs:enumeration value="EMail"/>
						<xs:enumeration value="End"/>
						<xs:enumeration value="Fax"/>
						<xs:enumeration value="FeeAmount"/>
						<xs:enumeration value="ForceCapture"/>
						<xs:enumeration value="FraudPostprocessResult"/>
						<xs:enumeration value="FraudPreprocessResult"/>
						<xs:enumeration value="GetExpressCheckout"/>
						<xs:enumeration value="GetStatus"/>
						<xs:enumeration value="HTTPCommitResult"/>
						<xs:enumeration value="HTTPCommitResults"/>
						<xs:enumeration value="HostCode"/>
						<xs:enumeration value="HostResponse"/>
						<xs:enumeration value="HostURL"/>
						<xs:enumeration value="IAVSResult"/>
						<xs:enumeration value="Inquiry"/>
						<xs:enumeration value="IntegrationType"/>
						<xs:enumeration value="IntegrationVersion"/>
						<xs:enumeration value="InvNum"/>
						<xs:enumeration value="JavaVersion"/>
						<xs:enumeration value="MaxFailPayments"/>
						<xs:enumeration value="Message"/>
						<xs:enumeration value="Modify"/>
						<xs:enumeration value="Name"/>
						<xs:enumeration value="NextPayment"/>
						<xs:enumeration value="Note"/>
						<xs:enumeration value="NumFailedPayments"/>
						<xs:enumeration value="OSArchitecture"/>
						<xs:enumeration value="OSName"/>
						<xs:enumeration value="OSVersion"/>
						<xs:enumeration value="OptionalTrans"/>
						<xs:enumeration value="OptionalTransAmt"/>
						<xs:enumeration value="OrigMessage"/>
						<xs:enumeration value="OrigPNRef"/>
						<xs:enumeration value="OrigProfileID"/>
						<xs:enumeration value="OrigResult"/>
						<xs:enumeration value="PAReq"/>
						<xs:enumeration value="PARes"/>
						<xs:enumeration value="PNRef"/>
						<xs:enumeration value="PPRef"/>
						<xs:enumeration value="Partner"/>
						<xs:enumeration value="Password"/>
						<xs:enumeration value="PayPalResult"/>
						<xs:enumeration value="PayPeriod"/>
						<xs:enumeration value="PayerID"/>
						<xs:enumeration value="PayerStatus"/>
						<xs:enumeration value="Payment"/>
						<xs:enumeration value="PaymentHistory"/>
						<xs:enumeration value="PaymentNum"/>
						<xs:enumeration value="PaymentType"/>
						<xs:enumeration value="PaymentsLeft"/>
						<xs:enumeration value="PendingReason"/>
						<xs:enumeration value="Phone"/>
						<xs:enumeration value="ProcessorResult"/>
						<xs:enumeration value="ProfileID"/>
						<xs:enumeration value="Proxy"/>
						<xs:enumeration value="RMSID"/>
						<xs:enumeration value="RPData"/>
						<xs:enumeration value="RPPaymentResult"/>
						<xs:enumeration value="RPRef"/>
						<xs:enumeration value="RRN"/>
						<xs:enumeration value="Reactivate"/>
						<xs:enumeration value="ReceiptData"/>
						<xs:enumeration value="ReceiptURL"/>
						<xs:enumeration value="RecurringProfile"/>
						<xs:enumeration value="RecurringProfileResult"/>
						<xs:enumeration value="RecurringProfileResults"/>
						<xs:enumeration value="RecurringProfiles"/>
						<xs:enumeration value="RepeatSale"/>
						<xs:enumeration value="RequestAuth"/>
						<xs:enumeration value="RequestData"/>
						<xs:enumeration value="ResponseData"/>
						<xs:enumeration value="ResponseText"/>
						<xs:enumeration value="Result"/>
						<xs:enumeration value="RetryNumDays"/>
						<xs:enumeration value="STAN"/>
						<xs:enumeration value="Sale"/>
						<xs:enumeration value="SetExpressCheckout"/>
						<xs:enumeration value="SettleDate"/>
						<xs:enumeration value="ShipTo"/>
						<xs:enumeration value="Start"/>
						<xs:enumeration value="Status"/>
						<xs:enumeration value="StreetMatch"/>
						<xs:enumeration value="Tender"/>
						<xs:enumeration value="Term"/>
						<xs:enumeration value="Token"/>
						<xs:enumeration value="TotalAmt"/>
						<xs:enumeration value="TrStatus"/>
						<xs:enumeration value="TransState"/>
						<xs:enumeration value="TransTime"/>
						<xs:enumeration value="Transaction"/>
						<xs:enumeration value="TransactionReceipts"/>
						<xs:enumeration value="TransactionResult"/>
						<xs:enumeration value="TransactionResults"/>
						<xs:enumeration value="TransactionUpdate"/>
						<xs:enumeration value="Transactions"/>
						<xs:enumeration value="User"/>
						<xs:enumeration value="UserDomain"/>
						<xs:enumeration value="UserPass"/>
						<xs:enumeration value="ValidateAuthentication"/>
						<xs:enumeration value="Vendor"/>
						<xs:enumeration value="Verbosity"/>
						<xs:enumeration value="VerifyEnrollment"/>
						<xs:enumeration value="VersionIntegrationTracking"/>
						<xs:enumeration value="Void"/>
						<xs:enumeration value="WrapperType"/>
						<xs:enumeration value="WrapperVersion"/>
						<xs:enumeration value="XID"/>
						<xs:enumeration value="XMLData"/>
						<xs:enumeration value="XMLPayReceipt"/>
						<xs:enumeration value="XMLPayRequest"/>
						<xs:enumeration value="XMLPayResponse"/>
						<xs:enumeration value="ZipMatch"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="minOccurs">
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="maxOccurs">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="1"/>
						<xs:enumeration value="unbounded"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="complexType">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="choice"/>
				<xs:element ref="element" maxOccurs="unbounded"/>
				<xs:sequence>
					<xs:element ref="sequence"/>
					<xs:sequence minOccurs="0">
						<xs:element ref="attribute" maxOccurs="unbounded"/>
						<xs:element ref="element" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="content" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="elementOnly"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="choice">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="element" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute">
		<xs:complexType>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ID"/>
						<xs:enumeration value="ReferenceIdType"/>
						<xs:enumeration value="boolean"/>
						<xs:enumeration value="int"/>
						<xs:enumeration value="string"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="CustRef"/>
						<xs:enumeration value="Duplicate"/>
						<xs:enumeration value="Id"/>
						<xs:enumeration value="Timeout"/>
						<xs:enumeration value="request_id"/>
						<xs:enumeration value="response_id"/>
						<xs:enumeration value="version"/>
						<xs:enumeration value="xmlns"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cuker/merchant-gateways/lib/merchant_gateways/tests/billing/gateways/schemas/xmlpay/XMLPay_2001.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.paypal.com/XMLPay"xsd="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLPay_2001.xsd">
	<include schemaLocation="XMLPayTypes_2001.xsd"/>
	<element name="XMLPayRequest">
		<complexType content="elementOnly">
			<sequence>
				<element ref="RequestData"/>
				<element ref="RequestAuth"/>
			</sequence>
			<attribute name="version" type="string"/>
			<attribute name="request_id" type="string"/>
			<attribute name="response_id" type="string"/>
			<attribute name="Timeout" type="int"/>
		</complexType>
	</element>
	<element name="VersionIntegrationTracking">
		<complexType content="elementOnly">
			<sequence>
				<element name="IntegrationType" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="IntegrationVersion" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="WrapperType" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="WrapperVersion" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="OSName" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="OSArchitecture" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="OSVersion" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="JavaVersion" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="Proxy" type="string" minOccurs="0" maxOccurs="1"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="RequestData">
		<complexType content="elementOnly">
			<sequence>
				<element name="Vendor" type="UserIdType"/>
				<element name="Partner" type="UserIdType"/>
				<choice>
					<element name="Transactions">
						<complexType content="elementOnly">
							<element ref="Transaction" minOccurs="1" maxOccurs="unbounded"/>
						</complexType>
					</element>
					<element name="RecurringProfiles">
						<complexType content="elementOnly">
							<element ref="RecurringProfile" minOccurs="1" maxOccurs="unbounded"/>
						</complexType>
					</element>
					<element name="AccountUpdateRequests">
						<complexType content="elementOnly">
							<element ref="AccountUpdateRequest" minOccurs="1" maxOccurs="unbounded"/>
						</complexType>
					</element>
				</choice>
				<element ref="VersionIntegrationTracking" minOccurs="0" maxOccurs="1"/>
			</sequence>
		</complexType>
	</element>
	<element name="RequestAuth">
		<complexType content="elementOnly">
			<choice>
				<element ref="UserPass"/>
				<element ref="Signature"/>
			</choice>
		</complexType>
	</element>
	<element name="XMLPayResponse">
		<complexType content="elementOnly">
			<sequence>
				<element ref="ResponseData"/>
				<element ref="Signature" minOccurs="0" maxOccurs="1"/>
				<element name="TransactionReceipts" minOccurs="0" maxOccurs="1">
					<complexType content="elementOnly">
						<element ref="XMLPayReceipt" minOccurs="1" maxOccurs="unbounded"/>
					</complexType>
				</element>
			</sequence>
			<attribute name="xmlns" type="string"/>
			<attribute name="version" type="string"/>
			<attribute name="request_id" type="string"/>
			<attribute name="response_id" type="string"/>
		</complexType>
	</element>
	<element name="ResponseData">
		<complexType content="elementOnly">
			<sequence>
				<element name="Vendor" type="UserIdType"/>
				<element name="Partner" type="UserIdType"/>
				<choice>
					<element name="TransactionResults">
						<complexType content="elementOnly">
							<element ref="TransactionResult" minOccurs="1" maxOccurs="unbounded"/>
						</complexType>
					</element>
					<element name="RecurringProfileResults">
						<complexType content="elementOnly">
							<element ref="RecurringProfileResult" minOccurs="1" maxOccurs="unbounded"/>
						</complexType>
					</element>
					<element name="AccountUpdateResults">
						<complexType content="elementOnly">
							<element ref="AccountUpdateResult" minOccurs="1" maxOccurs="unbounded"/>
						</complexType>
					</element>
					<element name="HTTPCommitResults">
						<complexType content="elementOnly">
							<element ref="HTTPCommitResult" minOccurs="1" maxOccurs="unbounded"/>
						</complexType>
					</element>
				</choice>
			</sequence>
		</complexType>
	</element>
	<element name="XMLPayReceipt">
		<complexType content="elementOnly">
			<sequence>
				<element ref="ReceiptData"/>
				<element ref="Signature" minOccurs="0" maxOccurs="1"/>
			</sequence>
		</complexType>
	</element>
	<element name="ReceiptData">
		<complexType content="elementOnly">
			<sequence>
				<element name="Vendor" type="UserIdType"/>
				<element name="Partner" type="UserIdType"/>
				<element ref="Transaction"/>
				<element ref="TransactionResult"/>
			</sequence>
		</complexType>
	</element>
	<element name="Transaction">
		<complexType content="elementOnly">
			<sequence>
				<choice>
					<element ref="Authorization"/>
					<element ref="Capture"/>
					<element ref="Sale"/>
					<element ref="Credit"/>
					<element ref="Void"/>
					<element ref="ForceCapture"/>
					<element ref="RepeatSale"/>
					<element ref="GetStatus"/>
					<element ref="VerifyEnrollment"/>
					<element ref="ValidateAuthentication"/>
					<element ref="TransactionUpdate"/>
					<element ref="SetExpressCheckout"/>
					<element ref="GetExpressCheckout"/>
					<element ref="DoExpressCheckout"/>
				</choice>
			</sequence>
			<attribute name="Id" type="ID"/>
			<attribute name="CustRef" type="ReferenceIdType"/>
			<element name="Verbosity" type="VerbosityEnum" minOccurs="0" maxOccurs="1"/>
			<element name="BrowserUserAgent" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="BrowserTime" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="BrowserCountryCode" type="string" minOccurs="0" maxOccurs="1"/>
		</complexType>
	</element>
	<simpleType name="VerbosityEnum" base="string">
		<enumeration value="Off"/>
		<enumeration value="Low"/>
		<enumeration value="Medium"/>
		<enumeration value="High"/>
	</simpleType>
	<element name="Authorization">
		<complexType content="elementOnly">
			<sequence>
				<element ref="PayData"/>
				<element ref="PayDataAuth" minOccurs="0" maxOccurs="1"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="Capture">
		<complexType content="elementOnly">
			<sequence>
				<choice>
					<element name="PNRef" type="PNRefType"/>
					<element name="PPRef" type="PPRefType"/>
				</choice>
				<element ref="Invoice" minOccurs="0" maxOccurs="1"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="Sale">
		<complexType content="elementOnly">
			<sequence>
				<element ref="PayData"/>
				<element ref="PayDataAuth" minOccurs="0" maxOccurs="1"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="Credit">
		<complexType content="elementOnly">
			<sequence>
				<choice>
					<element name="PNRef" type="PNRefType"/>
					<element name="PPRef" type="PPRefType"/>
					<element ref="Tender"/>
				</choice>
				<element ref="Invoice" minOccurs="0" maxOccurs="1"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="Void">
		<complexType content="elementOnly">
			<sequence>
				<choice>
					<element name="PNRef" type="PNRefType"/>
					<element name="PPRef" type="PPRefType"/>
				</choice>
				<element name="Note" type="string" minOccurs="0" maxOccurs="1"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="ForceCapture">
		<complexType content="elementOnly">
			<sequence>
				<element ref="PayData"/>
				<element ref="PayDataAuth" minOccurs="0" maxOccurs="1"/>
				<element name="AuthCode" type="AuthCodeType"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="RepeatSale">
		<complexType content="elementOnly">
			<sequence>
				<element name="PNRef" type="PNRefType"/>
				<element ref="Invoice" minOccurs="0" maxOccurs="1"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="GetStatus">
		<complexType content="elementOnly">
			<sequence>
				<element name="PNRef" type="PNRefType"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="VerifyEnrollment">
		<complexType content="elementOnly">
			<sequence>
				<element ref="PayData"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="ValidateAuthentication">
		<complexType content="elementOnly">
			<sequence>
				<element name="PARes" type="BuyerAuthMesgType"/>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<element name="AccountUpdateRequest">
		<complexType content="elementOnly">
			<sequence>
				<element name="Action" type="AUActionEnum"/>
				<choice>
					<element name="PNRef" type="PNRefType"/>
					<element ref="Tender"/>
				</choice>
				<element ref="ExtData" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<simpleType name="TransactionUpdateActionEnum" base="string">
		<enumeration value="Approve"/>
		<enumeration value="Review"/>
		<enumeration value="ServiceDecline"/>
		<enumeration value="MerchantDecline"/>
	</simpleType>
	<element name="TransactionUpdate">
